name: hello world

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displays hello world msg
        run: echo "hello world, wes"

      - name: Another Task
        run: echo "another task...."
